-- =====================================================================
-- MM BGIMS — Normalized Relational Database Tables for Apply Form
-- Database Dialect: PostgreSQL (Native Supabase/PostgreSQL)
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. PERSONAL DETAILS TABLE
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS personal (
    -- Shared application ID generated by client (e.g. BGIMS-XXXXXX)
    id VARCHAR(50) PRIMARY KEY,
    
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    dob DATE NOT NULL,
    gender VARCHAR(20) NOT NULL,
    address TEXT NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    pin VARCHAR(10) NOT NULL
);

-- Indexing personal details for quick searches
CREATE INDEX IF NOT EXISTS personal_email_idx ON personal (email);
CREATE INDEX IF NOT EXISTS personal_name_idx ON personal (first_name, last_name);


-- ---------------------------------------------------------------------
-- 2. ACADEMIC RECORDS TABLE
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS academic (
    -- Maps 1-to-1 with personal info, cascading deletes
    application_id VARCHAR(50) PRIMARY KEY REFERENCES personal(id) ON DELETE CASCADE,
    
    x_board VARCHAR(100) NOT NULL,
    x_year INTEGER NOT NULL,
    x_score VARCHAR(20) NOT NULL,
    
    xii_board VARCHAR(100) NOT NULL,
    xii_year INTEGER NOT NULL,
    xii_score VARCHAR(20) NOT NULL,
    
    ug_university VARCHAR(255),
    ug_programme VARCHAR(255),
    ug_score VARCHAR(20),
    
    entrance_test VARCHAR(100),
    entrance_year INTEGER,
    entrance_score VARCHAR(20)
);


-- ---------------------------------------------------------------------
-- 3. PROGRAMME / ADMISSION DETAILS TABLE
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS programme (
    application_id VARCHAR(50) PRIMARY KEY REFERENCES personal(id) ON DELETE CASCADE,
    
    -- Course code selected (e.g. 'MBA-BF', 'MMS', 'BMS', 'PHD')
    programme_id VARCHAR(20) NOT NULL,
    
    -- Statement of Purpose essay text
    sop TEXT,
    
    -- Recommender contact
    ref_name VARCHAR(100),
    ref_email VARCHAR(255),
    
    -- Admission review status: 'submitted', 'shortlisted', 'interviewed', 'offered', 'rejected'
    status VARCHAR(30) DEFAULT 'submitted' NOT NULL,
    
    submitted_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Indexing for sorting cohort submissions and status filters
CREATE INDEX IF NOT EXISTS prog_programme_id_idx ON programme (programme_id);
CREATE INDEX IF NOT EXISTS prog_status_idx ON programme (status);
CREATE INDEX IF NOT EXISTS prog_submitted_at_idx ON programme (submitted_at);


-- ---------------------------------------------------------------------
-- 4. DOCUMENTATION UPLOADS TABLE
-- ---------------------------------------------------------------------
-- Tracks marksheet and ID proof scans uploaded to Supabase Storage.
CREATE TABLE IF NOT EXISTS document (
    id BIGSERIAL PRIMARY KEY,
    
    -- Foreign key to applicant
    application_id VARCHAR(50) REFERENCES personal(id) ON DELETE CASCADE,
    
    -- Document type uploaded (e.g. 'doc_class_x', 'doc_class_xii', 'doc_graduation', etc.)
    document_type VARCHAR(50) NOT NULL,
    
    -- File path inside the 'documentations' storage bucket
    file_path TEXT NOT NULL,
    
    uploaded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    -- Unique constraint to prevent duplicate type uploads for the same applicant
    CONSTRAINT unique_app_doc_type UNIQUE (application_id, document_type)
);

CREATE INDEX IF NOT EXISTS doc_app_id_idx ON document (application_id);


-- ---------------------------------------------------------------------
-- 5. PAYMENT TRANSACTIONS TABLE
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payments (
    -- Razorpay Transaction ID (e.g. pay_xxxxxxxxxxxx)
    id VARCHAR(100) PRIMARY KEY,
    
    application_id VARCHAR(50) REFERENCES personal(id) ON DELETE CASCADE,
    
    -- Captured fee amount (e.g. "Rs. 1,770")
    amount VARCHAR(20) NOT NULL,
    
    -- Payment gateway method used ('upi', 'card', 'netbanking', 'wallet')
    method VARCHAR(20) NOT NULL,
    
    captured_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS pay_app_id_idx ON payments (application_id);
